# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z-aDoGFePuaNxvaVQv5pGSUMNB-6zizg
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')
# Для работы с данными
import pandas as pd
import numpy as np

# Для визуализации
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

path = "/content/drive/MyDrive/creditcard.csv"
df = pd.read_csv(path)
df.head()

print("Размер датасета:", df.shape)
df.info()

# Количество пропусков в каждом столбце
print(df.isnull().sum().sum())        # общее количество пропусков
print(df.isnull().sum())              # по столбцам

# Описательная статистика
df.describe()

class_counts = df['Class'].value_counts()
print("Абсолютные частоты:\n", class_counts)
print("\nОтносительные частоты (в %):\n", df['Class'].value_counts(normalize=True) * 100)

plt.figure(figsize=(6,4))
sns.countplot(x='Class', data=df)
plt.title('Распределение классов (0 – легитимные, 1 – мошенничества)')
plt.show()

df['Hour'] = (df['Time'] // 3600) % 24

fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 8), sharex=True)
sns.histplot(df[df['Class']==0]['Hour'], bins=24, color='blue', ax=ax1, alpha=0.7)
ax1.set_title('Легитимные транзакции по часам')
ax1.set_ylabel('Количество')
sns.histplot(df[df['Class']==1]['Hour'], bins=24, color='red', ax=ax2, alpha=0.7)
ax2.set_title('Мошеннические транзакции по часам')
ax2.set_xlabel('Час дня')
ax2.set_ylabel('Количество')
plt.tight_layout()
plt.show()

# Статистика сумм
print(df['Amount'].describe())

# Гистограмма с логарифмической шкалой
plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
sns.histplot(df['Amount'], bins=100, kde=True)
plt.title('Распределение суммы транзакций (линейная шкала)')
plt.subplot(1,2,2)
sns.histplot(df['Amount'], bins=100, kde=True, log_scale=True)
plt.title('Распределение суммы транзакций (логарифмическая шкала)')
plt.show()

# Boxplot по классам (логарифмическая шкала)
plt.figure(figsize=(8,5))
sns.boxplot(x='Class', y='Amount', data=df)
plt.yscale('log')
plt.title('Распределение суммы транзакций по классам')
plt.xlabel('Class (0 – legitimate, 1 – fraud)')
plt.ylabel('Amount (log scale)')
plt.show()

# Список всех V-столбцов
pca_cols = [f'V{i}' for i in range(1, 29)]

# Boxplot для нескольких компонент, наиболее коррелирующих с Class (по результатам позже)
# Выделим компоненты с наибольшей абсолютной корреляцией (найдём позже)
# Пока построим для всех (4x7 сетка) – может занять время, но информативно
# Рисуем сетку 4x7
fig, axes = plt.subplots(4, 7, figsize=(20, 12))
axes = axes.flatten()

for i, col in enumerate(pca_cols):
    sns.boxplot(x='Class', y=col, data=df, ax=axes[i])
    axes[i].set_title(col)
    axes[i].set_xlabel('')
    axes[i].set_ylabel('')

plt.tight_layout()
plt.show()

# Считаем связь каждого признака с Class
corr = df.corr()['Class'].sort_values(ascending=False)
print(corr)

# Берём 6 самых сильных по модулю
top_pca = corr.abs().drop('Class').nlargest(6).index.tolist()
print("Самые важные V-признаки:", top_pca)

# Рисуем их отдельно
fig, axes = plt.subplots(2, 3, figsize=(15, 8))
axes = axes.flatten()

for i, col in enumerate(top_pca):
    sns.boxplot(x='Class', y=col, data=df, ax=axes[i])
    axes[i].set_title(col)

plt.tight_layout()
plt.show()