# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/162REaRNjwJu1QE1EfcpoAfNo0Z5356xz
"""

from google.colab import drive
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, precision_recall_curve, auc
import matplotlib.pyplot as plt

drive.mount('/content/drive')
path = "/content/drive/MyDrive/creditcard.csv"
df = pd.read_csv(path)
df.head()
X = df.drop('Class', axis=1)
Y = df['Class']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state=11, stratify=Y)

scaler = StandardScaler()
X_train[['Amount', 'Time']] = scaler.fit_transform(X_train[['Amount', 'Time']])
X_test[['Amount', 'Time']] = scaler.transform(X_test[['Amount', 'Time']])

model = LogisticRegression(random_state=52,max_iter=1000)
model.fit(X_train, Y_train)

y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:, 1]

f1 = f1_score(Y_test, y_pred)
precision, recall, _ = precision_recall_curve(Y_test, y_proba)
pr_auc = auc(recall, precision)

print(f"Базовый F1-Score: {f1:.4f}")
print(f"Базовый Precision-Recall AUC: {pr_auc:.4f}")
plt.figure(figsize=(6,4))
plt.plot(recall, precision, marker='.', label='PR-кривая')
plt.xlabel('Полнота (Recall)')
plt.ylabel('Точность (Precision)')
plt.title('Precision-Recall кривая')
plt.legend()
plt.grid(True)
plt.show()

from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler

results = {}

model_weighted = LogisticRegression(random_state=52, max_iter=1000, class_weight="balanced")
model_weighted.fit(X_train, Y_train)

y_weight_pred = model_weighted.predict(X_test)
y_weight_proba = model_weighted.predict_proba(X_test)[:,1]

precision_w, recall_w, _ = precision_recall_curve(Y_test, y_weight_proba)
results['Class Weighting'] = {
    'F1-Score': f1_score(Y_test, y_weight_pred),
    'Precision-Recall AUC' : auc(recall_w, precision_w)
}

smote = SMOTE(random_state=42)
X_train_smote, Y_train_smote = smote.fit_resample(X_train, Y_train)

model_smote = LogisticRegression(random_state=52, max_iter=1000)
model_smote.fit(X_train_smote, Y_train_smote)

y_smote_pred = model_smote.predict(X_test)
y_smote_proba = model_smote.predict_proba(X_test)[:,1]

precision_smote, recall_smote, _ = precision_recall_curve(Y_test, y_smote_proba)
results['SMOTE'] = {
    'F1-Score' : f1_score(Y_test, y_smote_pred),
    'Precision-Recall AUC' : auc(recall_smote, precision_smote)
}

random_under_sampler = RandomUnderSampler(random_state=52)
X_undersampling_train, Y_undersampling_train = random_under_sampler.fit_resample(X_train, Y_train)

model_undersampling = LogisticRegression(random_state=52, max_iter=1000)
model_undersampling.fit(X_undersampling_train, Y_undersampling_train)

y_undersampling_pred = model_undersampling.predict(X_test)
y_undersampling_proba = model_undersampling.predict_proba(X_test)[:,1]

precision_undersampling, recall_undersampling, _ = precision_recall_curve(Y_test, y_undersampling_proba)
results['RandomUnderSampling'] = {
    'F1-Score' : f1_score(Y_test, y_undersampling_pred),
    'Precision-Recall AUC' : auc(recall_undersampling, precision_undersampling)
}

comparison_df = pd.DataFrame(results).T
print(comparison_df)